include-warnings: true
exclude-checks:
  - check_1
include-checks:
  - check_2
minimum-severity: medium

key:
  platform: true
  package: true
  v1-key: android com.example.app

filters:
  valid-filter:
    include-warnings: false
    exclude-checks:
      - check_3
    include-checks:
      - check_4
    minimum-severity: info

summary: long

configs:
  empty: {}
  inline-filter:
    filter:
      include-warnings: true
      exclude-checks:
        - check_5
      include-checks:
        - check_6
      minimum-severity: low
  reference-filter:
    filter: valid-filter
  key-params-1:
    key:
      platform: true
      package: false
      v1-key: ios com.example.app
  key-params-2:
    key:
      platform: false
      package: true
  summary:
    summary: none
