name: "NowSecure: Create Issues"
description: "Create GitHub issues after NowSecure analysis"
author: "NowSecure Inc."
inputs:
  platform_token:
    required: true
    description: "NowSecure Platform token."
  github_token:
    required: false
    default: ${{ github.token }}
  api_url:
    required: false
    description: "NowSecure GraphQL API endpoint."
    default: "https://api.nowsecure.com"
  lab_api_url:
    required: false
    description: "NowSecure Lab API endpoint."
    default: "https://lab-api.nowsecure.com"
  lab_url:
    required: false
    description: "NowSecure webserver URL."
    default: "https://app.nowsecure.com"
  lab_type:
    required: false
    description: '"rainier" or "classic": The type of server referred to by lab_url'
    default: "rainier"
  config_path:
    required: false
    description: "Path containing .nsconfig.yml"
    default: ""
  config:
    required: false
    description: "Name of the configuration in .nsconfig.yml to use"
    default: ""
  report_id:
    required: true
    description: "The report ID."
  poll_interval_ms:
    required: false
    description: "Interval to poll Platform for application details. Default is once a minute."
    default: "60000"
  repo:
    required: false
    description: The name of the GitHub repository used to create issues. Defaults to the repo running the action"
  repo_owner:
    required: false
    description: "The owner of the GitHub repository used to create issues. Defaults to the owner of the repo running the action"
runs:
  using: "node16"
  main: "../dist/nowsecure-create-issues/index.js"
branding:
  icon: alert-triangle
  color: red
