name: "NowSecure: Convert SARIF"
description: "Convert NowSecure assessment to SARIF to be uploaded to GHAS"
author: "NowSecure Inc."
inputs:
  token:
    required: true
    description: "NowSecure Platform token."
  api_url:
    required: false
    description: "NowSecure GraphQL API endpoint."
    default: "https://api.nowsecure.com"
  lab_api_url:
    required: false
    description: "NowSecure Lab API endpoint."
    default: "https://lab-api.nowsecure.com"
  lab_url:
    required: false
    description: "NowSecure Lab URL."
    default: "https://lab.nowsecure.com"
  config_path:
    required: false
    description: "Path containing .nsconfig.yml"
    default: "."
  poll_interval_ms:
    required: false
    description: "Interval to poll Platform for application details. Default is once a minute."
    default: "60000"
  enable_sarif:
    required: false
    description: "Enable creation of a SARIF file."
    default: true
  enable_dependencies:
    required: false
    description: "Enable posting of dependencies results to GitHub."
    default: false
  group_id:
    required: true
    description: "Group ID for the application in Platform."
  report_id:
    required: false
    description: "The report ID."
runs:
  using: "node16"
  main: "../dist/nowsecure-convert-sarif/index.js"
branding:
  icon: alert-triangle
  color: red
