name: "NowSecure: Convert SARIF"
description: "Convert NowSecure assessment to SARIF to be uploaded to GHAS"
author: "NowSecure Inc."
inputs:
  platform_token:
    required: true
    description: "NowSecure Platform token."
  group_id:
    required: true
    description: "Group ID for the application in Platform."
  github_token:
    required: false
    default: ${{ github.token }}
  api_url:
    required: false
    description: "NowSecure GraphQL API endpoint."
    default: "https://api.nowsecure.com"
  lab_api_url:
    required: false
    description: "NowSecure Lab API endpoint."
    default: "https://lab-api.nowsecure.com"
  lab_url:
    required: false
    description: "NowSecure webserver URL."
    default: "https://app.nowsecure.com"
  lab_type:
    required: false
    description: '"rainier" or "classic": The type of server referred to by lab_url'
    default: "rainier"
  config_path:
    required: false
    description: "Path containing .nsconfig.yml"
    default: ""
  config:
    required: false
    description: "Name of the configuration in .nsconfig.yml to use"
    default: ""
  report_id:
    required: false
    description: "The report ID."
  poll_interval_ms:
    required: false
    description: "Interval to poll Platform for application details. Default is once a minute."
    default: "60000"
  enable_sarif:
    required: false
    description: "Enable creation of a SARIF file."
    default: true
  enable_dependencies:
    required: false
    description: "Enable posting of dependencies results to GitHub."
    default: false
  github_correlator:
    required: false
    description: "Used for the correlator field in the SBOM format. Distinguishes independent Workflows."
    default: ${{ format('{0}_{1}', github.workflow, github.job) }}
runs:
  using: "node16"
  main: "../dist/nowsecure-convert-sarif/index.js"
branding:
  icon: alert-triangle
  color: red
