# Copyright © 2023 NowSecure Inc.
#
# SPDX-License-Identifier: MIT

name: Builder

on:
  push:
    paths:
      - src/**
      - package.json
      - yarn.lock

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile --silent

      - run: |
          rm -rf dist
          yarn prepare-release

      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Build $(git rev-parse --short HEAD)" -a
          git push
